[options]
interval = 3 # How often to run checks in minutes
verbose = false # Verbose logging. true or false

[telegram]
api = "" # Telegram bot API key
chat = "" # Chat to post to, usually a negative number